layout_spectrum: 0.2080659
typography_spectrum: 0.4443971
color:
  saturation: 0.3872653
  lightness: 0.7299779
  brandStrength: 0.0722405
  rhythmicContrast: 0.7006769
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Drawings and Paintings by ErosArts
